// Generates .env.local with locally-random passwords.
// Idempotent: refuses to overwrite an existing file, so running it twice is safe.
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const TARGET = ".env.local";
if (existsSync(TARGET)) {
  console.log(`${TARGET} already exists — leaving it untouched.`);
  process.exit(0);
}

const pw = () => randomBytes(24).toString("base64url");
const [superPw, ownerPw, runtimePw, authPw] = [pw(), pw(), pw(), pw()];
const secret = randomBytes(32).toString("base64");

// The generated connection URLs must point at the SAME port docker-compose
// publishes, or a second clone on this machine ends up with its own container
// on a new port while still connecting to the first clone's database. So this
// honours NEXTUP_DB_PORT and writes it back into .env.local, where compose
// reads it from. Default unchanged.
const PORT = process.env.NEXTUP_DB_PORT || "55433";
const PROJECT = process.env.COMPOSE_PROJECT_NAME || "";
const HOST = `127.0.0.1:${PORT}`;

writeFileSync(
  TARGET,
  `# Generated by \`npm run env:init\`. Local development only. Git-ignored.
NEXTUP_DB_PORT=${PORT}
${PROJECT ? `COMPOSE_PROJECT_NAME=${PROJECT}\n` : ""}POSTGRES_PASSWORD=${superPw}
NEXTUP_OWNER_PASSWORD=${ownerPw}
NEXTUP_RUNTIME_PASSWORD=${runtimePw}
NEXTUP_AUTH_PASSWORD=${authPw}
POSTGRES_SUPERUSER_URL=postgresql://postgres:${superPw}@${HOST}/nextup
MIGRATION_DATABASE_URL=postgresql://nextup_owner:${ownerPw}@${HOST}/nextup
DATABASE_URL=postgresql://nextup_runtime:${runtimePw}@${HOST}/nextup
AUTH_DATABASE_URL=postgresql://nextup_auth:${authPw}@${HOST}/nextup
BETTER_AUTH_SECRET=${secret}
BETTER_AUTH_URL=http://localhost:3100
`,
  { mode: 0o600 },
);
console.log(`Wrote ${TARGET} with locally-generated passwords (db port ${PORT}).`);
