// Generates .env.local with locally-random passwords.
// Idempotent: refuses to overwrite an existing file, so running it twice is safe.
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const TARGET = ".env.local";
if (existsSync(TARGET)) {
  console.log(`${TARGET} already exists — leaving it untouched.`);
  process.exit(0);
}

const pw = () => randomBytes(24).toString("base64url");
const [superPw, ownerPw, runtimePw] = [pw(), pw(), pw()];
const HOST = "127.0.0.1:55433";

writeFileSync(
  TARGET,
  `# Generated by \`npm run env:init\`. Local development only. Git-ignored.
POSTGRES_PASSWORD=${superPw}
NEXTUP_OWNER_PASSWORD=${ownerPw}
NEXTUP_RUNTIME_PASSWORD=${runtimePw}
POSTGRES_SUPERUSER_URL=postgresql://postgres:${superPw}@${HOST}/nextup
MIGRATION_DATABASE_URL=postgresql://nextup_owner:${ownerPw}@${HOST}/nextup
DATABASE_URL=postgresql://nextup_runtime:${runtimePw}@${HOST}/nextup
`,
  { mode: 0o600 },
);
console.log(`Wrote ${TARGET} with locally-generated passwords.`);
